// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Excel.Template.Recette.xl.worksheets
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_Projects\Azure\facturation-api\src\Excel\Template\Recette\xl\worksheets\sheet3_xml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class sheet3_xml : sheet3_xmlBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n<worksheet xmlns=\"http:/" +
                    "/schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.ope" +
                    "nxmlformats.org/officeDocument/2006/relationships\" xmlns:mc=\"http://schemas.open" +
                    "xmlformats.org/markup-compatibility/2006\" mc:Ignorable=\"x14ac xr xr2 xr3\" xmlns:" +
                    "x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\" xmlns:xr=\"ht" +
                    "tp://schemas.microsoft.com/office/spreadsheetml/2014/revision\" xmlns:xr2=\"http:/" +
                    "/schemas.microsoft.com/office/spreadsheetml/2015/revision2\" xmlns:xr3=\"http://sc" +
                    "hemas.microsoft.com/office/spreadsheetml/2016/revision3\" xr:uid=\"{42DA807B-968C-" +
                    "4482-9A4D-F9C5738F8756}\">\r\n  <dimension ref=\"A1:L30\"/>\r\n  <sheetViews>\r\n    <she" +
                    "etView workbookViewId=\"0\">\r\n      <selection activeCell=\"G12\" sqref=\"G12\"/>\r\n   " +
                    " </sheetView>\r\n  </sheetViews>\r\n  <sheetFormatPr baseColWidth=\"10\" defaultColWid" +
                    "th=\"8.7265625\" defaultRowHeight=\"14.5\" x14ac:dyDescent=\"0.35\"/>\r\n  <cols>\r\n    <" +
                    "col min=\"1\" max=\"1\" width=\"13.08984375\" customWidth=\"1\"/>\r\n    <col min=\"2\" max=" +
                    "\"2\" width=\"20.7265625\" customWidth=\"1\"/>\r\n    <col min=\"3\" max=\"3\" width=\"23.542" +
                    "96875\" customWidth=\"1\"/>\r\n    <col min=\"4\" max=\"4\" width=\"16.7265625\" customWidt" +
                    "h=\"1\"/>\r\n    <col min=\"5\" max=\"5\" width=\"21\" customWidth=\"1\"/>\r\n    <col min=\"6\"" +
                    " max=\"6\" width=\"25.453125\" customWidth=\"1\"/>\r\n    <col min=\"7\" max=\"7\" width=\"20" +
                    ".26953125\" customWidth=\"1\"/>\r\n    <col min=\"8\" max=\"8\" width=\"29.26953125\" custo" +
                    "mWidth=\"1\"/>\r\n  </cols>\r\n  <sheetData>\r\n    <row r=\"1\" spans=\"1:12\" ht=\"23.5\" x1" +
                    "4ac:dyDescent=\"0.55000000000000004\">\r\n      <c r=\"A1\" s=\"5\" t=\"s\">\r\n        <v>1" +
                    "0</v>\r\n      </c>\r\n      <c r=\"B1\" s=\"1\"/>\r\n      <c r=\"C1\" s=\"2\" t=\"s\">\r\n      " +
                    "  <v>0</v>\r\n      </c>\r\n      <c r=\"D1\" s=\"3\">\r\n        <v>2018</v>\r\n      </c>\r" +
                    "\n      <c r=\"E1\" s=\"4\"/>\r\n      <c r=\"F1\" s=\"39\" t=\"s\">\r\n        <v>62</v>\r\n    " +
                    "  </c>\r\n      <c r=\"G1\" s=\"40\">\r\n        <f>SUM(E7:E15)</f>\r\n        <v>68330</v" +
                    ">\r\n      </c>\r\n      <c r=\"H1\" s=\"4\"/>\r\n    </row>\r\n    <row r=\"2\" spans=\"1:12\" " +
                    "ht=\"21\" x14ac:dyDescent=\"0.5\">\r\n      <c r=\"A2\" s=\"6\"/>\r\n      <c r=\"B2\" s=\"7\"/>" +
                    "\r\n      <c r=\"C2\" s=\"18\"/>\r\n      <c r=\"D2\" s=\"18\"/>\r\n    </row>\r\n    <row r=\"3\"" +
                    " spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A3\" s=\"6\"/>\r\n      <c r=\"B3\" " +
                    "s=\"7\"/>\r\n      <c r=\"J3\" s=\"10\"/>\r\n    </row>\r\n    <row r=\"4\" spans=\"1:12\" ht=\"1" +
                    "8.5\" x14ac:dyDescent=\"0.45\">\r\n      <c r=\"A4\" s=\"15\" t=\"s\">\r\n        <v>1</v>\r\n " +
                    "     </c>\r\n      <c r=\"B4\" s=\"16\"/>\r\n      <c r=\"C4\" s=\"17\"/>\r\n      <c r=\"D4\" s" +
                    "=\"17\"/>\r\n      <c r=\"E4\" s=\"17\"/>\r\n      <c r=\"F4\" s=\"17\"/>\r\n      <c r=\"G4\" s=\"" +
                    "17\"/>\r\n      <c r=\"H4\" s=\"17\"/>\r\n      <c r=\"I4\" s=\"11\"/>\r\n      <c r=\"J4\" s=\"11" +
                    "\"/>\r\n      <c r=\"K4\" s=\"11\"/>\r\n      <c r=\"L4\" s=\"11\"/>\r\n    </row>\r\n    <row r=" +
                    "\"5\" spans=\"1:12\" ht=\"18.5\" x14ac:dyDescent=\"0.45\">\r\n      <c r=\"A5\" s=\"12\"/>\r\n  " +
                    "    <c r=\"B5\" s=\"13\"/>\r\n      <c r=\"C5\" s=\"14\"/>\r\n      <c r=\"D5\" s=\"14\"/>\r\n    " +
                    "  <c r=\"E5\" s=\"14\"/>\r\n      <c r=\"F5\" s=\"14\"/>\r\n      <c r=\"G5\" s=\"14\"/>\r\n      " +
                    "<c r=\"H5\" s=\"14\"/>\r\n      <c r=\"I5\" s=\"11\"/>\r\n      <c r=\"J5\" s=\"11\"/>\r\n      <c" +
                    " r=\"K5\" s=\"11\"/>\r\n      <c r=\"L5\" s=\"11\"/>\r\n    </row>\r\n    <row r=\"6\" spans=\"1:" +
                    "12\" ht=\"15.5\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A6\" s=\"23\" t=\"s\">\r\n        <v" +
                    ">2</v>\r\n      </c>\r\n      <c r=\"B6\" s=\"24\" t=\"s\">\r\n        <v>3</v>\r\n      </c>\r" +
                    "\n      <c r=\"C6\" s=\"25\" t=\"s\">\r\n        <v>4</v>\r\n      </c>\r\n      <c r=\"D6\" s=" +
                    "\"25\" t=\"s\">\r\n        <v>5</v>\r\n      </c>\r\n      <c r=\"E6\" s=\"25\" t=\"s\">\r\n      " +
                    "  <v>6</v>\r\n      </c>\r\n      <c r=\"F6\" s=\"8\" t=\"s\">\r\n        <v>7</v>\r\n      </" +
                    "c>\r\n      <c r=\"G6\" s=\"8\" t=\"s\">\r\n        <v>8</v>\r\n      </c>\r\n      <c r=\"H6\" " +
                    "s=\"8\" t=\"s\">\r\n        <v>9</v>\r\n      </c>\r\n    </row>\r\n    <row r=\"7\" spans=\"1:" +
                    "12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A7\" s=\"26\">\r\n        <v>43193</v>\r\n    " +
                    "  </c>\r\n      <c r=\"B7\" s=\"27\" t=\"s\">\r\n        <v>38</v>\r\n      </c>\r\n      <c r" +
                    "=\"C7\" s=\"28\" t=\"s\">\r\n        <v>30</v>\r\n      </c>\r\n      <c r=\"D7\" s=\"29\" t=\"s\"" +
                    ">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E7\" s=\"36\">\r\n        <v>6840</v>\r\n" +
                    "      </c>\r\n      <c r=\"F7\" s=\"22\">\r\n        <f>(1+G7)*E7</f>\r\n        <v>6840</" +
                    "v>\r\n      </c>\r\n      <c r=\"G7\" s=\"19\">\r\n        <v>0</v>\r\n      </c>\r\n      <c " +
                    "r=\"H7\" t=\"s\">\r\n        <v>14</v>\r\n      </c>\r\n    </row>\r\n    <row r=\"8\" spans=\"" +
                    "1:12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A8\" s=\"30\">\r\n        <v>43217</v>\r\n  " +
                    "    </c>\r\n      <c r=\"B8\" s=\"31\" t=\"s\">\r\n        <v>39</v>\r\n      </c>\r\n      <c" +
                    " r=\"C8\" s=\"10\" t=\"s\">\r\n        <v>30</v>\r\n      </c>\r\n      <c r=\"D8\" s=\"29\" t=\"" +
                    "s\">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E8\" s=\"41\">\r\n        <v>6080</v>" +
                    "\r\n      </c>\r\n      <c r=\"F8\" s=\"22\">\r\n        <f t=\"shared\" ref=\"F8:F15\" si=\"0\"" +
                    ">(1+G8)*E8</f>\r\n        <v>6080</v>\r\n      </c>\r\n      <c r=\"G8\" s=\"19\">\r\n      " +
                    "  <v>0</v>\r\n      </c>\r\n      <c r=\"H8\" t=\"s\">\r\n        <v>17</v>\r\n      </c>\r\n " +
                    "   </row>\r\n    <row r=\"9\" spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A9\" " +
                    "s=\"32\">\r\n        <v>43251</v>\r\n      </c>\r\n      <c r=\"B9\" s=\"31\" t=\"s\">\r\n      " +
                    "  <v>40</v>\r\n      </c>\r\n      <c r=\"C9\" s=\"10\" t=\"s\">\r\n        <v>30</v>\r\n     " +
                    " </c>\r\n      <c r=\"D9\" s=\"29\" t=\"s\">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=" +
                    "\"E9\" s=\"41\">\r\n        <v>6460</v>\r\n      </c>\r\n      <c r=\"F9\" s=\"22\">\r\n        " +
                    "<f t=\"shared\" si=\"0\"/>\r\n        <v>6460</v>\r\n      </c>\r\n      <c r=\"G9\" s=\"19\">" +
                    "\r\n        <v>0</v>\r\n      </c>\r\n      <c r=\"H9\" t=\"s\">\r\n        <v>17</v>\r\n     " +
                    " </c>\r\n    </row>\r\n    <row r=\"10\" spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r\n      <" +
                    "c r=\"A10\" s=\"32\">\r\n        <v>43283</v>\r\n      </c>\r\n      <c r=\"B10\" s=\"31\" t=\"" +
                    "s\">\r\n        <v>41</v>\r\n      </c>\r\n      <c r=\"C10\" s=\"10\" t=\"s\">\r\n        <v>3" +
                    "0</v>\r\n      </c>\r\n      <c r=\"D10\" s=\"29\" t=\"s\">\r\n        <v>13</v>\r\n      </c>" +
                    "\r\n      <c r=\"E10\" s=\"41\">\r\n        <v>7220</v>\r\n      </c>\r\n      <c r=\"F10\" s=" +
                    "\"22\">\r\n        <f t=\"shared\" si=\"0\"/>\r\n        <v>7220</v>\r\n      </c>\r\n      <c" +
                    " r=\"G10\" s=\"19\">\r\n        <v>0</v>\r\n      </c>\r\n      <c r=\"H10\" t=\"s\">\r\n       " +
                    " <v>14</v>\r\n      </c>\r\n    </row>\r\n    <row r=\"11\" spans=\"1:12\" x14ac:dyDescent" +
                    "=\"0.35\">\r\n      <c r=\"A11\" s=\"32\">\r\n        <v>43312</v>\r\n      </c>\r\n      <c r" +
                    "=\"B11\" s=\"31\" t=\"s\">\r\n        <v>42</v>\r\n      </c>\r\n      <c r=\"C11\" s=\"10\" t=\"" +
                    "s\">\r\n        <v>30</v>\r\n      </c>\r\n      <c r=\"D11\" s=\"29\" t=\"s\">\r\n        <v>1" +
                    "3</v>\r\n      </c>\r\n      <c r=\"E11\" s=\"41\">\r\n        <v>4750</v>\r\n      </c>\r\n  " +
                    "    <c r=\"F11\" s=\"22\">\r\n        <f t=\"shared\" si=\"0\"/>\r\n        <v>4750</v>\r\n   " +
                    "   </c>\r\n      <c r=\"G11\" s=\"19\">\r\n        <v>0</v>\r\n      </c>\r\n      <c r=\"H11" +
                    "\" t=\"s\">\r\n        <v>17</v>\r\n      </c>\r\n    </row>\r\n    <row r=\"12\" spans=\"1:12" +
                    "\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A12\" s=\"32\">\r\n        <v>43343</v>\r\n     " +
                    " </c>\r\n      <c r=\"B12\" s=\"31\" t=\"s\">\r\n        <v>43</v>\r\n      </c>\r\n      <c r" +
                    "=\"C12\" s=\"10\" t=\"s\">\r\n        <v>30</v>\r\n      </c>\r\n      <c r=\"D12\" s=\"29\" t=\"" +
                    "s\">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E12\" s=\"41\">\r\n        <v>7220</v" +
                    ">\r\n      </c>\r\n      <c r=\"F12\" s=\"22\">\r\n        <f t=\"shared\" si=\"0\"/>\r\n       " +
                    " <v>7220</v>\r\n      </c>\r\n      <c r=\"G12\" s=\"19\">\r\n        <v>0</v>\r\n      </c>" +
                    "\r\n      <c r=\"H12\" t=\"s\">\r\n        <v>17</v>\r\n      </c>\r\n    </row>\r\n    <row r" +
                    "=\"13\" spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A13\" s=\"35\" t=\"s\">\r\n    " +
                    "    <v>45</v>\r\n      </c>\r\n      <c r=\"B13\" s=\"37\" t=\"s\">\r\n        <v>46</v>\r\n  " +
                    "    </c>\r\n      <c r=\"C13\" s=\"34\" t=\"s\">\r\n        <v>44</v>\r\n      </c>\r\n      <" +
                    "c r=\"D13\" s=\"29\" t=\"s\">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E13\" s=\"42\">" +
                    "\r\n        <v>10560</v>\r\n      </c>\r\n      <c r=\"F13\" s=\"22\">\r\n        <f t=\"shar" +
                    "ed\" si=\"0\"/>\r\n        <v>12672</v>\r\n      </c>\r\n      <c r=\"G13\" s=\"19\">\r\n      " +
                    "  <v>0.2</v>\r\n      </c>\r\n      <c r=\"H13\" s=\"43\" t=\"s\">\r\n        <v>17</v>\r\n   " +
                    "   </c>\r\n      <c r=\"I13\" s=\"9\"/>\r\n    </row>\r\n    <row r=\"14\" spans=\"1:12\" x14a" +
                    "c:dyDescent=\"0.35\">\r\n      <c r=\"A14\" s=\"35\" t=\"s\">\r\n        <v>52</v>\r\n      </" +
                    "c>\r\n      <c r=\"B14\" s=\"37\" t=\"s\">\r\n        <v>47</v>\r\n      </c>\r\n      <c r=\"C" +
                    "14\" s=\"34\" t=\"s\">\r\n        <v>44</v>\r\n      </c>\r\n      <c r=\"D14\" s=\"29\" t=\"s\">" +
                    "\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E14\" s=\"42\">\r\n        <v>9600</v>\r\n" +
                    "      </c>\r\n      <c r=\"F14\" s=\"22\">\r\n        <f t=\"shared\" si=\"0\"/>\r\n        <v" +
                    ">11520</v>\r\n      </c>\r\n      <c r=\"G14\" s=\"19\">\r\n        <v>0.2</v>\r\n      </c>" +
                    "\r\n      <c r=\"H14\" s=\"43\" t=\"s\">\r\n        <v>17</v>\r\n      </c>\r\n    </row>\r\n   " +
                    " <row r=\"15\" spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A15\" s=\"35\" t=\"s\"" +
                    ">\r\n        <v>53</v>\r\n      </c>\r\n      <c r=\"B15\" s=\"37\" t=\"s\">\r\n        <v>48<" +
                    "/v>\r\n      </c>\r\n      <c r=\"C15\" s=\"34\" t=\"s\">\r\n        <v>44</v>\r\n      </c>\r\n" +
                    "      <c r=\"D15\" s=\"29\" t=\"s\">\r\n        <v>13</v>\r\n      </c>\r\n      <c r=\"E15\" " +
                    "s=\"42\">\r\n        <v>9600</v>\r\n      </c>\r\n      <c r=\"F15\" s=\"22\">\r\n        <f t" +
                    "=\"shared\" si=\"0\"/>\r\n        <v>11520</v>\r\n      </c>\r\n      <c r=\"G15\" s=\"19\">\r\n" +
                    "        <v>0.2</v>\r\n      </c>\r\n      <c r=\"H15\" s=\"43\" t=\"s\">\r\n        <v>17</v" +
                    ">\r\n      </c>\r\n    </row>\r\n    <row r=\"16\" spans=\"1:12\" x14ac:dyDescent=\"0.35\">\r" +
                    "\n      <c r=\"A16\" s=\"35\"/>\r\n      <c r=\"B16\" s=\"37\"/>\r\n      <c r=\"C16\" s=\"34\"/>" +
                    "\r\n      <c r=\"D16\" s=\"29\"/>\r\n      <c r=\"E16\" s=\"38\"/>\r\n      <c r=\"F16\" s=\"22\"/" +
                    ">\r\n      <c r=\"G16\" s=\"19\"/>\r\n      <c r=\"H16\" s=\"43\"/>\r\n    </row>\r\n    <row r=" +
                    "\"17\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A17\" s=\"35\"/>\r\n      <c r=" +
                    "\"B17\" s=\"37\"/>\r\n      <c r=\"C17\" s=\"34\"/>\r\n      <c r=\"D17\" s=\"29\"/>\r\n      <c r" +
                    "=\"E17\" s=\"38\"/>\r\n      <c r=\"F17\" s=\"22\"/>\r\n      <c r=\"G17\" s=\"19\"/>\r\n      <c " +
                    "r=\"H17\" s=\"43\"/>\r\n    </row>\r\n    <row r=\"18\" spans=\"1:8\" x14ac:dyDescent=\"0.35\"" +
                    ">\r\n      <c r=\"A18\" s=\"35\"/>\r\n      <c r=\"B18\" s=\"37\"/>\r\n      <c r=\"C18\" s=\"34\"" +
                    "/>\r\n      <c r=\"D18\" s=\"29\"/>\r\n      <c r=\"E18\" s=\"38\"/>\r\n      <c r=\"F18\" s=\"22" +
                    "\"/>\r\n      <c r=\"G18\" s=\"19\"/>\r\n      <c r=\"H18\" s=\"43\"/>\r\n    </row>\r\n    <row " +
                    "r=\"19\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A19\" s=\"35\"/>\r\n      <c " +
                    "r=\"B19\" s=\"37\"/>\r\n      <c r=\"C19\" s=\"34\"/>\r\n      <c r=\"D19\" s=\"29\"/>\r\n      <c" +
                    " r=\"E19\" s=\"38\"/>\r\n      <c r=\"F19\" s=\"22\"/>\r\n      <c r=\"G19\" s=\"19\"/>\r\n      <" +
                    "c r=\"H19\" s=\"43\"/>\r\n    </row>\r\n    <row r=\"20\" spans=\"1:8\" x14ac:dyDescent=\"0.3" +
                    "5\">\r\n      <c r=\"A20\" s=\"35\"/>\r\n      <c r=\"B20\" s=\"37\"/>\r\n      <c r=\"C20\" s=\"3" +
                    "4\"/>\r\n      <c r=\"D20\" s=\"29\"/>\r\n      <c r=\"E20\" s=\"38\"/>\r\n      <c r=\"F20\" s=\"" +
                    "22\"/>\r\n      <c r=\"G20\" s=\"19\"/>\r\n      <c r=\"H20\" s=\"43\"/>\r\n    </row>\r\n    <ro" +
                    "w r=\"21\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A21\" s=\"35\"/>\r\n      <" +
                    "c r=\"B21\" s=\"37\"/>\r\n      <c r=\"C21\" s=\"34\"/>\r\n      <c r=\"D21\" s=\"29\"/>\r\n      " +
                    "<c r=\"E21\" s=\"38\"/>\r\n      <c r=\"F21\" s=\"22\"/>\r\n      <c r=\"G21\" s=\"19\"/>\r\n     " +
                    " <c r=\"H21\" s=\"43\"/>\r\n    </row>\r\n    <row r=\"22\" spans=\"1:8\" x14ac:dyDescent=\"0" +
                    ".35\">\r\n      <c r=\"A22\" s=\"20\"/>\r\n      <c r=\"B22\" s=\"7\"/>\r\n    </row>\r\n    <row" +
                    " r=\"23\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A23\" s=\"20\"/>\r\n      <c" +
                    " r=\"B23\" s=\"7\"/>\r\n    </row>\r\n    <row r=\"24\" spans=\"1:8\" x14ac:dyDescent=\"0.35\"" +
                    ">\r\n      <c r=\"A24\" s=\"20\"/>\r\n      <c r=\"B24\" s=\"7\"/>\r\n    </row>\r\n    <row r=\"" +
                    "25\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A25\" s=\"20\"/>\r\n      <c r=\"" +
                    "B25\" s=\"7\"/>\r\n    </row>\r\n    <row r=\"26\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n " +
                    "     <c r=\"A26\" s=\"20\"/>\r\n      <c r=\"B26\" s=\"7\"/>\r\n    </row>\r\n    <row r=\"27\" " +
                    "spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A27\" s=\"20\"/>\r\n      <c r=\"B27\"" +
                    " s=\"7\"/>\r\n    </row>\r\n    <row r=\"28\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n     " +
                    " <c r=\"A28\" s=\"20\"/>\r\n      <c r=\"B28\" s=\"7\"/>\r\n    </row>\r\n    <row r=\"29\" span" +
                    "s=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c r=\"A29\" s=\"20\"/>\r\n      <c r=\"B29\" s=\"" +
                    "7\"/>\r\n    </row>\r\n    <row r=\"30\" spans=\"1:8\" x14ac:dyDescent=\"0.35\">\r\n      <c " +
                    "r=\"A30\" s=\"20\"/>\r\n      <c r=\"B30\" s=\"7\"/>\r\n    </row>\r\n  </sheetData>\r\n  <pageM" +
                    "argins left=\"0.7\" right=\"0.7\" top=\"0.75\" bottom=\"0.75\" header=\"0.3\" footer=\"0.3\"" +
                    "/>\r\n</worksheet>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class sheet3_xmlBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
