// ------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime : 16.0.0.0
//  
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Excel.Template.Recette.xl
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\_Projects\Azure\facturation-api\src\Excel\Template\Recette\xl\styles_xml.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class styles_xml : styles_xmlBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\r\n<styleSheet xmlns=\"http:" +
                    "//schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:mc=\"http://schemas.o" +
                    "penxmlformats.org/markup-compatibility/2006\" mc:Ignorable=\"x14ac x16r2 xr\" xmlns" +
                    ":x14ac=\"http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac\" xmlns:x16r2" +
                    "=\"http://schemas.microsoft.com/office/spreadsheetml/2015/02/main\" xmlns:xr=\"http" +
                    "://schemas.microsoft.com/office/spreadsheetml/2014/revision\">\r\n  <numFmts count=" +
                    "\"2\">\r\n    <numFmt numFmtId=\"44\" formatCode=\"_-* #,##0.00\\ &quot;€&quot;_-;\\-* #," +
                    "##0.00\\ &quot;€&quot;_-;_-* &quot;-&quot;??\\ &quot;€&quot;_-;_-@_-\"/>\r\n    <numF" +
                    "mt numFmtId=\"164\" formatCode=\"#,##0.00\\ &quot;€&quot;\"/>\r\n  </numFmts>\r\n  <fonts" +
                    " count=\"27\" x14ac:knownFonts=\"1\">\r\n    <font>\r\n      <sz val=\"11\"/>\r\n      <colo" +
                    "r theme=\"1\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <sche" +
                    "me val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"11\"/>\r\n      <color th" +
                    "eme=\"1\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme v" +
                    "al=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"18\"/>\r\n      <color theme=" +
                    "\"3\"/>\r\n      <name val=\"Calibri Light\"/>\r\n      <family val=\"2\"/>\r\n      <scheme" +
                    " val=\"major\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"15\"/>\r\n     " +
                    " <color theme=\"3\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n     " +
                    " <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"13\"/" +
                    ">\r\n      <color theme=\"3\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/" +
                    ">\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz v" +
                    "al=\"11\"/>\r\n      <color theme=\"3\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family " +
                    "val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"" +
                    "11\"/>\r\n      <color rgb=\"FF006100\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family" +
                    " val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=" +
                    "\"11\"/>\r\n      <color rgb=\"FF9C0006\"/>\r\n      <name val=\"Calibri\"/>\r\n      <famil" +
                    "y val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val" +
                    "=\"11\"/>\r\n      <color rgb=\"FF9C5700\"/>\r\n      <name val=\"Calibri\"/>\r\n      <fami" +
                    "ly val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz va" +
                    "l=\"11\"/>\r\n      <color rgb=\"FF3F3F76\"/>\r\n      <name val=\"Calibri\"/>\r\n      <fam" +
                    "ily val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r" +
                    "\n      <sz val=\"11\"/>\r\n      <color rgb=\"FF3F3F3F\"/>\r\n      <name val=\"Calibri\"/" +
                    ">\r\n      <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>" +
                    "\r\n      <b/>\r\n      <sz val=\"11\"/>\r\n      <color rgb=\"FFFA7D00\"/>\r\n      <name v" +
                    "al=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font" +
                    ">\r\n    <font>\r\n      <sz val=\"11\"/>\r\n      <color rgb=\"FFFA7D00\"/>\r\n      <name " +
                    "val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </fon" +
                    "t>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"11\"/>\r\n      <color theme=\"0\"/>\r\n    " +
                    "  <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n " +
                    "   </font>\r\n    <font>\r\n      <sz val=\"11\"/>\r\n      <color rgb=\"FFFF0000\"/>\r\n   " +
                    "   <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n" +
                    "    </font>\r\n    <font>\r\n      <i/>\r\n      <sz val=\"11\"/>\r\n      <color rgb=\"FF7" +
                    "F7F7F\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme va" +
                    "l=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"11\"/>\r\n      <c" +
                    "olor theme=\"1\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <s" +
                    "cheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"11\"/>\r\n      <color" +
                    " theme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <schem" +
                    "e val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"14\"/>\r\n    " +
                    "  <color theme=\"1\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n    " +
                    "  <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"16\"" +
                    "/>\r\n      <color theme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"" +
                    "/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <i/>" +
                    "\r\n      <u/>\r\n      <sz val=\"18\"/>\r\n      <color theme=\"9\" tint=\"-0.249977111117" +
                    "893\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=" +
                    "\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"16\"/>\r\n      <color theme=\"0\"" +
                    "/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=\"min" +
                    "or\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"14\"/>\r\n      <color t" +
                    "heme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme " +
                    "val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <sz val=\"14\"/>\r\n      <color theme" +
                    "=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <scheme val=" +
                    "\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <sz val=\"12\"/>\r\n      <col" +
                    "or theme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <family val=\"2\"/>\r\n      <sch" +
                    "eme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n      <b/>\r\n      <i/>\r\n      <u/>\r\n" +
                    "      <sz val=\"18\"/>\r\n      <color theme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n   " +
                    "   <family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n    <font>\r\n    " +
                    "  <sz val=\"18\"/>\r\n      <color theme=\"0\"/>\r\n      <name val=\"Calibri\"/>\r\n      <" +
                    "family val=\"2\"/>\r\n      <scheme val=\"minor\"/>\r\n    </font>\r\n  </fonts>\r\n  <fills" +
                    " count=\"36\">\r\n    <fill>\r\n      <patternFill patternType=\"none\"/>\r\n    </fill>\r\n" +
                    "    <fill>\r\n      <patternFill patternType=\"gray125\"/>\r\n    </fill>\r\n    <fill>\r" +
                    "\n      <patternFill patternType=\"solid\">\r\n        <fgColor rgb=\"FFC6EFCE\"/>\r\n   " +
                    "   </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"soli" +
                    "d\">\r\n        <fgColor rgb=\"FFFFC7CE\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <" +
                    "fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor rgb=\"FFFFEB9C\"/" +
                    ">\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType" +
                    "=\"solid\">\r\n        <fgColor rgb=\"FFFFCC99\"/>\r\n      </patternFill>\r\n    </fill>\r" +
                    "\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor rgb=\"FFF2" +
                    "F2F2\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patte" +
                    "rnType=\"solid\">\r\n        <fgColor rgb=\"FFA5A5A5\"/>\r\n      </patternFill>\r\n    </" +
                    "fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor rgb" +
                    "=\"FFFFFFCC\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill" +
                    " patternType=\"solid\">\r\n        <fgColor theme=\"4\"/>\r\n      </patternFill>\r\n    <" +
                    "/fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor th" +
                    "eme=\"4\" tint=\"0.79998168889431442\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </p" +
                    "atternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n " +
                    "       <fgColor theme=\"4\" tint=\"0.59999389629810485\"/>\r\n        <bgColor indexed" +
                    "=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patte" +
                    "rnType=\"solid\">\r\n        <fgColor theme=\"4\" tint=\"0.39997558519241921\"/>\r\n      " +
                    "  <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      " +
                    "<patternFill patternType=\"solid\">\r\n        <fgColor theme=\"5\"/>\r\n      </pattern" +
                    "Fill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n       " +
                    " <fgColor theme=\"5\" tint=\"0.79998168889431442\"/>\r\n        <bgColor indexed=\"65\"/" +
                    ">\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType" +
                    "=\"solid\">\r\n        <fgColor theme=\"5\" tint=\"0.59999389629810485\"/>\r\n        <bgC" +
                    "olor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patte" +
                    "rnFill patternType=\"solid\">\r\n        <fgColor theme=\"5\" tint=\"0.3999755851924192" +
                    "1\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <f" +
                    "ill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor theme=\"6\"/>\r\n   " +
                    "   </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"soli" +
                    "d\">\r\n        <fgColor theme=\"6\" tint=\"0.79998168889431442\"/>\r\n        <bgColor i" +
                    "ndexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill" +
                    " patternType=\"solid\">\r\n        <fgColor theme=\"6\" tint=\"0.59999389629810485\"/>\r\n" +
                    "        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n" +
                    "      <patternFill patternType=\"solid\">\r\n        <fgColor theme=\"6\" tint=\"0.3999" +
                    "7558519241921\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </f" +
                    "ill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor them" +
                    "e=\"7\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patte" +
                    "rnType=\"solid\">\r\n        <fgColor theme=\"7\" tint=\"0.79998168889431442\"/>\r\n      " +
                    "  <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      " +
                    "<patternFill patternType=\"solid\">\r\n        <fgColor theme=\"7\" tint=\"0.5999938962" +
                    "9810485\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n" +
                    "    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor theme=\"7\" " +
                    "tint=\"0.39997558519241921\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFi" +
                    "ll>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <" +
                    "fgColor theme=\"8\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patte" +
                    "rnFill patternType=\"solid\">\r\n        <fgColor theme=\"8\" tint=\"0.7999816888943144" +
                    "2\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <f" +
                    "ill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor theme=\"8\" tint=\"" +
                    "0.59999389629810485\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n " +
                    "   </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColo" +
                    "r theme=\"8\" tint=\"0.39997558519241921\"/>\r\n        <bgColor indexed=\"65\"/>\r\n     " +
                    " </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\"" +
                    ">\r\n        <fgColor theme=\"9\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n" +
                    "      <patternFill patternType=\"solid\">\r\n        <fgColor theme=\"9\" tint=\"0.7999" +
                    "8168889431442\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </patternFill>\r\n    </f" +
                    "ill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n        <fgColor them" +
                    "e=\"9\" tint=\"0.59999389629810485\"/>\r\n        <bgColor indexed=\"65\"/>\r\n      </pat" +
                    "ternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill patternType=\"solid\">\r\n   " +
                    "     <fgColor theme=\"9\" tint=\"0.39997558519241921\"/>\r\n        <bgColor indexed=\"" +
                    "65\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill pattern" +
                    "Type=\"solid\">\r\n        <fgColor theme=\"2\" tint=\"-0.499984740745262\"/>\r\n        <" +
                    "bgColor indexed=\"64\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <pa" +
                    "tternFill patternType=\"solid\">\r\n        <fgColor theme=\"1\"/>\r\n        <bgColor i" +
                    "ndexed=\"64\"/>\r\n      </patternFill>\r\n    </fill>\r\n    <fill>\r\n      <patternFill" +
                    " patternType=\"solid\">\r\n        <fgColor theme=\"9\" tint=\"-0.249977111117893\"/>\r\n " +
                    "       <bgColor indexed=\"64\"/>\r\n      </patternFill>\r\n    </fill>\r\n  </fills>\r\n " +
                    " <borders count=\"13\">\r\n    <border>\r\n      <left/>\r\n      <right/>\r\n      <top/>" +
                    "\r\n      <bottom/>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left/>" +
                    "\r\n      <right/>\r\n      <top/>\r\n      <bottom style=\"thick\">\r\n        <color the" +
                    "me=\"4\"/>\r\n      </bottom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n     " +
                    " <left/>\r\n      <right/>\r\n      <top/>\r\n      <bottom style=\"thick\">\r\n        <c" +
                    "olor theme=\"4\" tint=\"0.499984740745262\"/>\r\n      </bottom>\r\n      <diagonal/>\r\n " +
                    "   </border>\r\n    <border>\r\n      <left/>\r\n      <right/>\r\n      <top/>\r\n      <" +
                    "bottom style=\"medium\">\r\n        <color theme=\"4\" tint=\"0.39997558519241921\"/>\r\n " +
                    "     </bottom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left styl" +
                    "e=\"thin\">\r\n        <color rgb=\"FF7F7F7F\"/>\r\n      </left>\r\n      <right style=\"t" +
                    "hin\">\r\n        <color rgb=\"FF7F7F7F\"/>\r\n      </right>\r\n      <top style=\"thin\">" +
                    "\r\n        <color rgb=\"FF7F7F7F\"/>\r\n      </top>\r\n      <bottom style=\"thin\">\r\n  " +
                    "      <color rgb=\"FF7F7F7F\"/>\r\n      </bottom>\r\n      <diagonal/>\r\n    </border>" +
                    "\r\n    <border>\r\n      <left style=\"thin\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n    " +
                    "  </left>\r\n      <right style=\"thin\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </" +
                    "right>\r\n      <top style=\"thin\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </top>\r" +
                    "\n      <bottom style=\"thin\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </bottom>\r\n" +
                    "      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left/>\r\n      <right/>\r\n " +
                    "     <top/>\r\n      <bottom style=\"double\">\r\n        <color rgb=\"FFFF8001\"/>\r\n   " +
                    "   </bottom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left style=" +
                    "\"double\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </left>\r\n      <right style=\"d" +
                    "ouble\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </right>\r\n      <top style=\"doub" +
                    "le\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </top>\r\n      <bottom style=\"double" +
                    "\">\r\n        <color rgb=\"FF3F3F3F\"/>\r\n      </bottom>\r\n      <diagonal/>\r\n    </b" +
                    "order>\r\n    <border>\r\n      <left style=\"thin\">\r\n        <color rgb=\"FFB2B2B2\"/>" +
                    "\r\n      </left>\r\n      <right style=\"thin\">\r\n        <color rgb=\"FFB2B2B2\"/>\r\n  " +
                    "    </right>\r\n      <top style=\"thin\">\r\n        <color rgb=\"FFB2B2B2\"/>\r\n      <" +
                    "/top>\r\n      <bottom style=\"thin\">\r\n        <color rgb=\"FFB2B2B2\"/>\r\n      </bot" +
                    "tom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left/>\r\n      <righ" +
                    "t/>\r\n      <top style=\"thin\">\r\n        <color theme=\"4\"/>\r\n      </top>\r\n      <" +
                    "bottom style=\"double\">\r\n        <color theme=\"4\"/>\r\n      </bottom>\r\n      <diag" +
                    "onal/>\r\n    </border>\r\n    <border>\r\n      <left style=\"thin\">\r\n        <color i" +
                    "ndexed=\"64\"/>\r\n      </left>\r\n      <right style=\"thin\">\r\n        <color indexed" +
                    "=\"64\"/>\r\n      </right>\r\n      <top style=\"thin\">\r\n        <color indexed=\"64\"/>" +
                    "\r\n      </top>\r\n      <bottom style=\"thin\">\r\n        <color indexed=\"64\"/>\r\n    " +
                    "  </bottom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left/>\r\n    " +
                    "  <right/>\r\n      <top/>\r\n      <bottom style=\"thin\">\r\n        <color theme=\"2\"/" +
                    ">\r\n      </bottom>\r\n      <diagonal/>\r\n    </border>\r\n    <border>\r\n      <left " +
                    "style=\"thin\">\r\n        <color indexed=\"64\"/>\r\n      </left>\r\n      <right style=" +
                    "\"thin\">\r\n        <color indexed=\"64\"/>\r\n      </right>\r\n      <top style=\"thin\">" +
                    "\r\n        <color indexed=\"64\"/>\r\n      </top>\r\n      <bottom/>\r\n      <diagonal/" +
                    ">\r\n    </border>\r\n  </borders>\r\n  <cellStyleXfs count=\"44\">\r\n    <xf numFmtId=\"0" +
                    "\" fontId=\"0\" fillId=\"0\" borderId=\"0\"/>\r\n    <xf numFmtId=\"44\" fontId=\"1\" fillId=" +
                    "\"0\" borderId=\"0\" applyFont=\"0\" applyFill=\"0\" applyBorder=\"0\" applyAlignment=\"0\" " +
                    "applyProtection=\"0\"/>\r\n    <xf numFmtId=\"9\" fontId=\"1\" fillId=\"0\" borderId=\"0\" a" +
                    "pplyFont=\"0\" applyFill=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0" +
                    "\"/>\r\n    <xf numFmtId=\"0\" fontId=\"2\" fillId=\"0\" borderId=\"0\" applyNumberFormat=\"" +
                    "0\" applyFill=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <" +
                    "xf numFmtId=\"0\" fontId=\"3\" fillId=\"0\" borderId=\"1\" applyNumberFormat=\"0\" applyFi" +
                    "ll=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"4\"" +
                    " fillId=\"0\" borderId=\"2\" applyNumberFormat=\"0\" applyFill=\"0\" applyAlignment=\"0\" " +
                    "applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"5\" fillId=\"0\" borderId=\"3\" a" +
                    "pplyNumberFormat=\"0\" applyFill=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n   " +
                    " <xf numFmtId=\"0\" fontId=\"5\" fillId=\"0\" borderId=\"0\" applyNumberFormat=\"0\" apply" +
                    "Fill=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFm" +
                    "tId=\"0\" fontId=\"6\" fillId=\"2\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\"" +
                    " applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"7\" fillI" +
                    "d=\"3\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" appl" +
                    "yProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"8\" fillId=\"4\" borderId=\"0\" apply" +
                    "NumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <" +
                    "xf numFmtId=\"0\" fontId=\"9\" fillId=\"5\" borderId=\"4\" applyNumberFormat=\"0\" applyAl" +
                    "ignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"10\" fillId=\"6\" b" +
                    "orderId=\"5\" applyNumberFormat=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    " +
                    "<xf numFmtId=\"0\" fontId=\"11\" fillId=\"6\" borderId=\"4\" applyNumberFormat=\"0\" apply" +
                    "Alignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"12\" fillId=\"0\"" +
                    " borderId=\"6\" applyNumberFormat=\"0\" applyFill=\"0\" applyAlignment=\"0\" applyProtec" +
                    "tion=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"13\" fillId=\"7\" borderId=\"7\" applyNumber" +
                    "Format=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId" +
                    "=\"14\" fillId=\"0\" borderId=\"0\" applyNumberFormat=\"0\" applyFill=\"0\" applyBorder=\"0" +
                    "\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fill" +
                    "Id=\"8\" borderId=\"8\" applyNumberFormat=\"0\" applyFont=\"0\" applyAlignment=\"0\" apply" +
                    "Protection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"15\" fillId=\"0\" borderId=\"0\" apply" +
                    "NumberFormat=\"0\" applyFill=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtectio" +
                    "n=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"16\" fillId=\"0\" borderId=\"9\" applyNumberFor" +
                    "mat=\"0\" applyFill=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId" +
                    "=\"0\" fontId=\"17\" fillId=\"9\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" a" +
                    "pplyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=" +
                    "\"10\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" apply" +
                    "Protection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"11\" borderId=\"0\" apply" +
                    "NumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <" +
                    "xf numFmtId=\"0\" fontId=\"1\" fillId=\"12\" borderId=\"0\" applyNumberFormat=\"0\" applyB" +
                    "order=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=" +
                    "\"17\" fillId=\"13\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignme" +
                    "nt=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"14\" border" +
                    "Id=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=" +
                    "\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"15\" borderId=\"0\" applyNumberForma" +
                    "t=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId" +
                    "=\"0\" fontId=\"1\" fillId=\"16\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" a" +
                    "pplyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"17\" fillId" +
                    "=\"17\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" appl" +
                    "yProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"18\" borderId=\"0\" appl" +
                    "yNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    " +
                    "<xf numFmtId=\"0\" fontId=\"1\" fillId=\"19\" borderId=\"0\" applyNumberFormat=\"0\" apply" +
                    "Border=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId" +
                    "=\"1\" fillId=\"20\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignme" +
                    "nt=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"17\" fillId=\"21\" borde" +
                    "rId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection" +
                    "=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"22\" borderId=\"0\" applyNumberForm" +
                    "at=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtI" +
                    "d=\"0\" fontId=\"1\" fillId=\"23\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" " +
                    "applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId" +
                    "=\"24\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" appl" +
                    "yProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"17\" fillId=\"25\" borderId=\"0\" app" +
                    "lyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n   " +
                    " <xf numFmtId=\"0\" fontId=\"1\" fillId=\"26\" borderId=\"0\" applyNumberFormat=\"0\" appl" +
                    "yBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontI" +
                    "d=\"1\" fillId=\"27\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignm" +
                    "ent=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"28\" borde" +
                    "rId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection" +
                    "=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"17\" fillId=\"29\" borderId=\"0\" applyNumberFor" +
                    "mat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmt" +
                    "Id=\"0\" fontId=\"1\" fillId=\"30\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\"" +
                    " applyAlignment=\"0\" applyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillI" +
                    "d=\"31\" borderId=\"0\" applyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" app" +
                    "lyProtection=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"1\" fillId=\"32\" borderId=\"0\" app" +
                    "lyNumberFormat=\"0\" applyBorder=\"0\" applyAlignment=\"0\" applyProtection=\"0\"/>\r\n  <" +
                    "/cellStyleXfs>\r\n  <cellXfs count=\"46\">\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"" +
                    "0\" borderId=\"0\" xfId=\"0\"/>\r\n    <xf numFmtId=\"0\" fontId=\"18\" fillId=\"0\" borderId" +
                    "=\"0\" xfId=\"0\" applyFont=\"1\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"ce" +
                    "nter\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"19\" fillId=\"33\" borderId=\"0\" xf" +
                    "Id=\"0\" applyFont=\"1\" applyFill=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"19\" fillId=\"3" +
                    "3\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyProtection=\"1\">\r\n     " +
                    " <protection locked=\"0\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"18\" fillId=\"0" +
                    "\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"20\" fillId" +
                    "=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fill" +
                    "Id=\"0\" borderId=\"0\" xfId=\"0\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"l" +
                    "eft\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=" +
                    "\"0\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"center\"/>\r\n    </xf>\r\n    " +
                    "<xf numFmtId=\"0\" fontId=\"24\" fillId=\"34\" borderId=\"10\" xfId=\"0\" applyFont=\"1\" ap" +
                    "plyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment vertical=\"cent" +
                    "er\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"11\" xfId=" +
                    "\"0\" applyBorder=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" x" +
                    "fId=\"0\" applyBorder=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"23\" fillId=\"0\" borderId=" +
                    "\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\"/>\r\n    <xf numFmtId=\"0\"" +
                    " fontId=\"22\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyA" +
                    "lignment=\"1\">\r\n      <alignment horizontal=\"left\"/>\r\n    </xf>\r\n    <xf numFmtId" +
                    "=\"0\" fontId=\"23\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" ap" +
                    "plyAlignment=\"1\">\r\n      <alignment horizontal=\"center\"/>\r\n    </xf>\r\n    <xf nu" +
                    "mFmtId=\"0\" fontId=\"23\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=" +
                    "\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"22\" fillId=\"35\" borderId=\"0\" xfId=\"0\" applyF" +
                    "ont=\"1\" applyFill=\"1\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"left\"/>\r" +
                    "\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"23\" fillId=\"35\" borderId=\"0\" xfId=\"0\" a" +
                    "pplyFont=\"1\" applyFill=\"1\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"cen" +
                    "ter\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"23\" fillId=\"35\" borderId=\"0\" xfI" +
                    "d=\"0\" applyFont=\"1\" applyFill=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"21\" fillId=\"0\"" +
                    " borderId=\"0\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\"/>\r\n    <xf numFmtId=\"9\" fontI" +
                    "d=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"2\" applyFont=\"1\"/>\r\n    <xf numFmtId=\"0\" fon" +
                    "tId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyAlignment=\"1\">\r\n      <alignment h" +
                    "orizontal=\"right\"/>\r\n    </xf>\r\n    <xf numFmtId=\"14\" fontId=\"0\" fillId=\"0\" bord" +
                    "erId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" applyAlignment=\"1\">\r\n      <alignment ho" +
                    "rizontal=\"right\"/>\r\n    </xf>\r\n    <xf numFmtId=\"164\" fontId=\"0\" fillId=\"0\" bord" +
                    "erId=\"0\" xfId=\"0\" applyNumberFormat=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"24\" fill" +
                    "Id=\"34\" borderId=\"12\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" apply" +
                    "Alignment=\"1\">\r\n      <alignment horizontal=\"left\" vertical=\"center\"/>\r\n    </xf" +
                    ">\r\n    <xf numFmtId=\"0\" fontId=\"24\" fillId=\"34\" borderId=\"12\" xfId=\"0\" applyFont" +
                    "=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment horizon" +
                    "tal=\"center\" vertical=\"center\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"24\" fi" +
                    "llId=\"34\" borderId=\"12\" xfId=\"0\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" app" +
                    "lyAlignment=\"1\">\r\n      <alignment vertical=\"center\"/>\r\n    </xf>\r\n    <xf numFm" +
                    "tId=\"14\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" apply" +
                    "Border=\"1\" applyAlignment=\"1\" applyProtection=\"1\">\r\n      <alignment horizontal=" +
                    "\"right\"/>\r\n      <protection locked=\"0\"/>\r\n    </xf>\r\n    <xf numFmtId=\"49\" font" +
                    "Id=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" applyBorder=\"1\" ap" +
                    "plyAlignment=\"1\" applyProtection=\"1\">\r\n      <alignment horizontal=\"center\"/>\r\n " +
                    "     <protection locked=\"0\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId" +
                    "=\"0\" borderId=\"0\" xfId=\"0\" applyBorder=\"1\" applyProtection=\"1\">\r\n      <protecti" +
                    "on locked=\"0\"/>\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=" +
                    "\"0\" xfId=\"0\" applyBorder=\"1\" applyAlignment=\"1\" applyProtection=\"1\">\r\n      <ali" +
                    "gnment horizontal=\"center\"/>\r\n      <protection locked=\"0\"/>\r\n    </xf>\r\n    <xf" +
                    " numFmtId=\"14\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\"" +
                    " applyBorder=\"1\"/>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId" +
                    "=\"0\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment horizontal=\"center\"/>" +
                    "\r\n    </xf>\r\n    <xf numFmtId=\"14\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" a" +
                    "pplyNumberFormat=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment horiz" +
                    "ontal=\"right\"/>\r\n    </xf>\r\n    <xf numFmtId=\"44\" fontId=\"0\" fillId=\"0\" borderId" +
                    "=\"0\" xfId=\"1\" applyFont=\"1\" applyBorder=\"1\"/>\r\n    <xf numFmtId=\"49\" fontId=\"0\" " +
                    "fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" applyFont=\"1\" applyFill=\"" +
                    "1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment wrapText=\"1\"/>\r\n    </x" +
                    "f>\r\n    <xf numFmtId=\"49\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumbe" +
                    "rFormat=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n   " +
                    "   <alignment horizontal=\"right\" wrapText=\"1\"/>\r\n    </xf>\r\n    <xf numFmtId=\"44" +
                    "\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"1\" applyFont=\"1\" applyBorder=\"1\" appl" +
                    "yAlignment=\"1\" applyProtection=\"1\">\r\n      <protection locked=\"0\"/>\r\n    </xf>\r\n" +
                    "    <xf numFmtId=\"49\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFor" +
                    "mat=\"1\" applyFont=\"1\" applyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <" +
                    "alignment horizontal=\"center\" wrapText=\"1\"/>\r\n    </xf>\r\n    <xf numFmtId=\"2\" fo" +
                    "ntId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" applyFont=\"1\" ap" +
                    "plyFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment wrapText=\"1\"/>" +
                    "\r\n    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"25\" fillId=\"35\" borderId=\"0\" xfId=\"0\" " +
                    "applyFont=\"1\" applyFill=\"1\"/>\r\n    <xf numFmtId=\"164\" fontId=\"26\" fillId=\"35\" bo" +
                    "rderId=\"0\" xfId=\"0\" applyNumberFormat=\"1\" applyFont=\"1\" applyFill=\"1\"/>\r\n    <xf" +
                    " numFmtId=\"44\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"1\" applyFont=\"1\"/>\r\n    " +
                    "<xf numFmtId=\"44\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"1\" applyFont=\"1\" appl" +
                    "yFill=\"1\" applyBorder=\"1\" applyAlignment=\"1\">\r\n      <alignment wrapText=\"1\"/>\r\n" +
                    "    </xf>\r\n    <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>\r\n " +
                    "   <xf numFmtId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>\r\n    <xf numFm" +
                    "tId=\"0\" fontId=\"0\" fillId=\"0\" borderId=\"0\" xfId=\"0\"/>\r\n  </cellXfs>\r\n  <cellStyl" +
                    "es count=\"44\">\r\n    <cellStyle name=\"20 % - Accent1\" xfId=\"21\" builtinId=\"30\" cu" +
                    "stomBuiltin=\"1\"/>\r\n    <cellStyle name=\"20 % - Accent2\" xfId=\"25\" builtinId=\"34\"" +
                    " customBuiltin=\"1\"/>\r\n    <cellStyle name=\"20 % - Accent3\" xfId=\"29\" builtinId=\"" +
                    "38\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"20 % - Accent4\" xfId=\"33\" builtinI" +
                    "d=\"42\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"20 % - Accent5\" xfId=\"37\" built" +
                    "inId=\"46\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"20 % - Accent6\" xfId=\"41\" bu" +
                    "iltinId=\"50\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Accent1\" xfId=\"22\"" +
                    " builtinId=\"31\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Accent2\" xfId=\"" +
                    "26\" builtinId=\"35\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Accent3\" xfI" +
                    "d=\"30\" builtinId=\"39\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Accent4\" " +
                    "xfId=\"34\" builtinId=\"43\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Accent" +
                    "5\" xfId=\"38\" builtinId=\"47\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"40 % - Acc" +
                    "ent6\" xfId=\"42\" builtinId=\"51\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"60 % - " +
                    "Accent1\" xfId=\"23\" builtinId=\"32\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"60 %" +
                    " - Accent2\" xfId=\"27\" builtinId=\"36\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"6" +
                    "0 % - Accent3\" xfId=\"31\" builtinId=\"40\" customBuiltin=\"1\"/>\r\n    <cellStyle name" +
                    "=\"60 % - Accent4\" xfId=\"35\" builtinId=\"44\" customBuiltin=\"1\"/>\r\n    <cellStyle n" +
                    "ame=\"60 % - Accent5\" xfId=\"39\" builtinId=\"48\" customBuiltin=\"1\"/>\r\n    <cellStyl" +
                    "e name=\"60 % - Accent6\" xfId=\"43\" builtinId=\"52\" customBuiltin=\"1\"/>\r\n    <cellS" +
                    "tyle name=\"Accent1\" xfId=\"20\" builtinId=\"29\" customBuiltin=\"1\"/>\r\n    <cellStyle" +
                    " name=\"Accent2\" xfId=\"24\" builtinId=\"33\" customBuiltin=\"1\"/>\r\n    <cellStyle nam" +
                    "e=\"Accent3\" xfId=\"28\" builtinId=\"37\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"A" +
                    "ccent4\" xfId=\"32\" builtinId=\"41\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Accen" +
                    "t5\" xfId=\"36\" builtinId=\"45\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Accent6\" " +
                    "xfId=\"40\" builtinId=\"49\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Avertissement" +
                    "\" xfId=\"16\" builtinId=\"11\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Calcul\" xfI" +
                    "d=\"13\" builtinId=\"22\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Cellule liée\" xf" +
                    "Id=\"14\" builtinId=\"24\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Entrée\" xfId=\"1" +
                    "1\" builtinId=\"20\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Insatisfaisant\" xfId" +
                    "=\"9\" builtinId=\"27\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Monétaire\" xfId=\"1" +
                    "\" builtinId=\"4\"/>\r\n    <cellStyle name=\"Neutre\" xfId=\"10\" builtinId=\"28\" customB" +
                    "uiltin=\"1\"/>\r\n    <cellStyle name=\"Normal\" xfId=\"0\" builtinId=\"0\"/>\r\n    <cellSt" +
                    "yle name=\"Note\" xfId=\"17\" builtinId=\"10\" customBuiltin=\"1\"/>\r\n    <cellStyle nam" +
                    "e=\"Pourcentage\" xfId=\"2\" builtinId=\"5\"/>\r\n    <cellStyle name=\"Satisfaisant\" xfI" +
                    "d=\"8\" builtinId=\"26\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Sortie\" xfId=\"12\"" +
                    " builtinId=\"21\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Texte explicatif\" xfId" +
                    "=\"18\" builtinId=\"53\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Titre\" xfId=\"3\" b" +
                    "uiltinId=\"15\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Titre 1\" xfId=\"4\" builti" +
                    "nId=\"16\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Titre 2\" xfId=\"5\" builtinId=\"" +
                    "17\" customBuiltin=\"1\"/>\r\n    <cellStyle name=\"Titre 3\" xfId=\"6\" builtinId=\"18\" c" +
                    "ustomBuiltin=\"1\"/>\r\n    <cellStyle name=\"Titre 4\" xfId=\"7\" builtinId=\"19\" custom" +
                    "Builtin=\"1\"/>\r\n    <cellStyle name=\"Total\" xfId=\"19\" builtinId=\"25\" customBuilti" +
                    "n=\"1\"/>\r\n    <cellStyle name=\"Vérification\" xfId=\"15\" builtinId=\"23\" customBuilt" +
                    "in=\"1\"/>\r\n  </cellStyles>\r\n  <dxfs count=\"0\"/>\r\n  <tableStyles count=\"0\" default" +
                    "TableStyle=\"TableStyleMedium2\" defaultPivotStyle=\"PivotStyleLight16\"/>\r\n  <extLs" +
                    "t>\r\n    <ext uri=\"{EB79DEF2-80B8-43e5-95BD-54CBDDF9020C}\" xmlns:x14=\"http://sche" +
                    "mas.microsoft.com/office/spreadsheetml/2009/9/main\">\r\n      <x14:slicerStyles de" +
                    "faultSlicerStyle=\"SlicerStyleLight1\"/>\r\n    </ext>\r\n    <ext uri=\"{9260A510-F301" +
                    "-46a8-8635-F512D64BE5F5}\" xmlns:x15=\"http://schemas.microsoft.com/office/spreads" +
                    "heetml/2010/11/main\">\r\n      <x15:timelineStyles defaultTimelineStyle=\"TimeSlice" +
                    "rStyleLight1\"/>\r\n    </ext>\r\n  </extLst>\r\n</styleSheet>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class styles_xmlBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
